version: "3.9"

services:
  eureka-server:
    build: ./eureka-server-security
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - flight-net

  config-server:
    build: ./config-server-webflux-security
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - flight-net

  api-gateway:
    build: ./api-gateway-security
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - flight-net

  user-service:
    build: ./user-service-security
    container_name: user-service
    ports:
      - "8091:8091"
    depends_on:
      - eureka-server
      - config-server
      - mongo
    networks:
      - flight-net

  flight-service:
    build: ./flight-service-security
    container_name: flight-service
    ports:
      - "8092:8092"
    depends_on:
      - eureka-server
      - config-server
      - mongo
    networks:
      - flight-net

  booking-service:
    build: ./booking-service-security
    container_name: booking-service
    ports:
      - "8093:8093"
    depends_on:
      - eureka-server
      - config-server
      - mongo
      - kafka
    networks:
      - flight-net

  notification-service:
    build: ./notification-service-security
    container_name: notification-service
    ports:
      - "8094:8094"
    depends_on:
      - eureka-server
      - config-server
      - kafka
    networks:
      - flight-net

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - flight-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - flight-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - flight-net

networks:
  flight-net:

volumes:
  mongo-data: